### PR TITLE
Add adapter start/stop to example. Add ble approved characteristics.

### PR DESCRIPTION
**Pull request by lepot311**
I've added an example of how to start/stop the adapter since none existed. This was a source of frustration when trying to use pygatt for the first time.

I've also filled out the ble characteristic constants to include all ble-approved values. A device now adds these to its characteristics so they can be queried. For instance, you can now check the battery level of a device with pygatt:

battery_characteristic = 0x2A19
battery_level, _ = self.conn.char_read(uuid16_to_uuid(battery_characteristic))

### CODE REVIEW

**Comment by lepot311** [comment]
Here are the failures:
./pygatt/backends/bgapi/bgapi.py:545:81: E501 line too long (82 > 80 characters)
./pygatt/backends/bgapi/constants.py:185:81: E501 line too long (83 > 80 characters)

Is E501 really necessary? Especially for something like a constants file.. I would recommend disabling E501 altogether and merging this..

**Comment by peplin** [comment]
Hey, thanks for the PR - it looks good and I'll merge soon, I just want to give it a test myself. The style validation is Python's PEP8 and we use the 80 char line limit. On that line you can add a line break like this:

```
'ieee_11073-20601_regulatory_certification_data_list': 
    bytearray([0x2A, 0x2A]),
```

(In cases where a natural line break is difficult, you can mark the end of a line with `# noqa` to skip PEP8 validation.)

**Comment by lepot311** [comment]
Are you waiting for me to add a line break and submit a new PR?

**Comment by peplin** [comment]
Yeah, we have branch protection on so that a PR failing the unit tests (including lint tests) can't accidentally be merged.

**Comment by lepot311** [comment]
Rock and roll

**Comment by peplin** [comment]
Great, thank you!

**Pull request merged**
