### PR TITLE
Add code to get the bluetooth adapter MAC address

### PR DESCRIPTION
**Pull request by lchish**
As requested!

### CODE REVIEW

**Comment by peplin** [comment]
Thanks! If you wouldn't mind wrapping the one long line to 80 characters, I'll merge this.

The lint error from the Travis CI run:

```
./pygatt/backends/bgapi/bgapi.py:113:81: E501 line too long (84 > 80 characters)
```

**Comment by lchish** [comment]
Looks all good now :)

**Comment by luzpaz** [comment]
Please consider merging this. Much needed function that effects downstream issues.

**Comment by peplin** [comment]
Thanks, sorry for the long delay.

**Pull request merged**
