### PR TITLE
Fix error on Windows, "No BGAPI compatible device detected"

### PR DESCRIPTION
**Pull request by designingSparks**
Fix issue #164

### CODE REVIEW

**Comment by lemarquois** [comment]
I run into exactly the same error and came up with the same fix

**Comment by draapho** [comment]
Actually, `time.sleep(0.5)` is useless in some situation.
The worst things I suffered in Windows is need `time.sleep(2)`
But, It is not necessary to add any time delay here.

The true problem here is in funciton `_open_serail_port`, there is a bug in this function causing only try once and having no chance to retry `max_connection_attemps`.

**Comment by mivola** [comment]
Using sleep is probably not the best idea, but this PR is: #181

**Comment by peplin** [comment]
Thanks - merged #181 for what I hope is the best possible fix, and #169 (a brief sleep) for good measure. I'm hoping to get something that works for the broadest set of people because I don't have a large variety of platforms to test with (just Linux).

**Pull request closed without merging**
