### PR TITLE
Support for multibyte notification messages in gatttool backend

### PR DESCRIPTION
**Pull request by IlyaSukhanov**

### CODE REVIEW

**Comment by peplin** [comment]
I want to do a quick sanity check on this, because I know I was using it fine before for multibyte notifications.

**Comment by IlyaSukhanov** [comment]
Makes sense. Just for the record this is exact problem I saw:

Message received by _handle_notification_string()
> Notification handle = 0x0018 value: d0 86 00 ff ff ff 0f 1d 05 00 00 00 3b 00 01 00 00 00 01 ec 

Error message generated
> Exception in thread Thread-1:
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>    self.run()
>  File "/usr/lib/python2.7/threading.py", line 754, in run
>    self.__target(*self.__args, **self.__kwargs)
>  File "/home/user/vcs/pygatt/pygatt/backends/gatttool/gatttool.py", line 366, in _receive
>    self._expect("fooooooo", timeout=.1)
>  File "/home/user/vcs/pygatt/pygatt/backends/gatttool/gatttool.py", line 296, in _expect
>    self._handle_notification_string(self._con.after)
>  File "/home/user/vcs/pygatt/pygatt/backends/gatttool/gatttool.py", line 306, in _handle_notification_string
>    hex_handle, _, hex_value = msg.strip().split()[3:]
>ValueError: too many values to unpack

I was thinking multibyte unpacking would have worked if some version of gatttool returned value without space separation. But there seems to have been another problem, the conversion of msg to bytestring it would convert the ascii representation of msg rather than the byte values. Specifically:
bytearray("55") vs bytearray([0x55]) (or bytearray("55".decode("hex"))).

**Comment by peplin** [comment]
What version of BlueZ/gatttool are you running?

**Comment by IlyaSukhanov** [comment]
Bluez 5.36-1 from debian.

**Comment by IlyaSukhanov** [comment]
This PR is deprecated by pr #43

**Pull request closed without merging**
