### PR TITLE
Clarify Python requirement in README and recommend the latest version.

### PR DESCRIPTION
**Pull request by ddddavidmartin**
I have seen two older Python versions (2.7 and 2.7.3) which fail to talk
to the USB adapter at all. They break during struct.unpack calls. The
latest versions 2.7.12 and 2.7.13 work fine though. I am not quite sure
which the lowest supported version is, so recommending the latest seems
a good compromise.

I'm happy for suggestions on how to phrase this best. I do think it is worth mentioning though in the README as we spent a bit of time looking into this issue before figuring out what the problem was.

### CODE REVIEW

**Comment by peplin** [comment]
Thanks! It sounds like there was a bug in struct.unpack that was fixed in 2.7.5: http://stackoverflow.com/questions/20612587/struct-unpack-with-bytearrays so I think we can be explicit in the README and say that 2.7.5 or greater are required.

**Comment by githubbrowser** [comment]
Ah yes, nice find! I agree, and I'll update the pull request.

**Comment by githubbrowser** [comment]
So, it has been a few days but I have not forgotten about this issue. I agree that we should be explicit in the version for the README.

But, for due diligence's sake I would like to confirm that Python 2.7.4 does not and 2.7.5 does work. I haven't been able to get them to run though when I had a look at it. The approach of "just uninstall the current version and install an older one" on my Windows VM did not work, as it still reported the latest for some reason.

Can anyone confirm that pygatt works with Python 2.7.5? Or any pointers on how to set up concurrent Python versions on Windows  / Mac? Thanks!

**Comment by peplin** [comment]
I'm going to merge this as-is since it's better than not mentioning the incompatibility at all. I don't see an easy way to install 2.7.5 in my environment without compiling from source.

**Pull request merged**
